[package]
name = "cargo-ledger"
version = "1.0.0"
authors = ["yhql"]
edition = "2018"

[dependencies]
cargo_metadata = "0.11.0"
clap = "3.0.0-beta.1"
goblin = "0.2.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"