---
name: Publish to Crates.io

on:
  push:
    branches:
      - main
      - mbr/fix-cargo-publish

permissions:
  contents: read

jobs:
  publish_crate:
    name: Publish rust crate
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_crates_deployment.yml@mbr/update-crate-deployment
    permissions:
      id-token: write
      attestations: write
      contents: write
    with:
      publish: true
      release: false

