---
name: Publish to Crates.io

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish_crate:
    name: Publish rust crate
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_crates_deployment.yml@v1
    with:
      publish: true
      release: false

